[tasks.ci]
script = '''
curl -sLO https://github.com/saadeghi/daisyui/releases/latest/download/daisyui.mjs
curl -sLO https://github.com/saadeghi/daisyui/releases/latest/download/daisyui-theme.mjs
dx build --web --fullstack true --force-sequential true --ssg --release --debug-symbols=false
'''

[tasks.fmt]
script = '''
dx fmt
cargo fmt --all -- --check
'''
